"""Generate handoff markdown files."""

import subprocess
from datetime import datetime
from pathlib import Path

from chase.config import ChaseConfig
from chase.cost import CostTracker
from chase.state import StateDir


def generate_handoff(
    state: StateDir,
    config: ChaseConfig,
    cost: CostTracker,
    current_sprint_id: int,
    status: str,
) -> Path:
    """Generate a handoff file summarizing session progress."""
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
    filename = f"{timestamp}_sprint{current_sprint_id}.md"
    handoff_path = state.handoffs / filename

    # Mission header
    mission_header = ""
    if state.mission_file.exists():
        lines = state.mission_file.read_text().split("\n")[:5]
        mission_header = "\n".join(lines)
    else:
        mission_header = "See MISSION.md"

    # Sprint summaries
    sprint_summaries = ""
    for eval_path in state.existing_evals():
        try:
            import json
            data = json.loads(eval_path.read_text())
            sid = eval_path.stem.split("-")[0]
            score = data.get("score", "?")
            verdict = data.get("verdict", "?")
            sprint_summaries += f"  - Sprint {sid}: score={score}, verdict={verdict}\n"
        except Exception:
            pass

    # Git info
    git_log = _git("log", "--oneline", "-10")
    git_diff_stat = _git("diff", "--stat")

    total_cost = cost.total_cost

    content = f"""# Handoff - {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Goal
{mission_header}

## Current Status
- Status: {status}
- Progress: Sprint {current_sprint_id}
- Total cost: ${total_cost:.4f} / ${config.cost_limit}

## Sprint Evaluation Summary
{sprint_summaries}

## Recent Commits
```
{git_log}
```

## Uncommitted Changes
{git_diff_stat}

## Next Steps
- Complete remaining sprints (from sprint {current_sprint_id + 1})
- Check NOTES.md for decision records

---
*Auto-generated by chase*
"""
    handoff_path.write_text(content)
    return handoff_path


def _git(*args: str) -> str:
    try:
        proc = subprocess.run(
            ["git"] + list(args),
            capture_output=True, text=True, timeout=10,
        )
        return proc.stdout.strip() or "no output"
    except Exception:
        return "unavailable"
